# Generated by Django 4.2.15 on 2026-07-31 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre_empresa', models.CharField(default='Callcenter IA', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('zona_horaria', models.CharField(default='America/Guayaquil', max_length=60)),
                ('minutos_incluidos_mes', models.IntegerField(default=3500)),
                ('correo_notificaciones', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_soporte', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('add', 'Creación'), ('change', 'Edición'), ('del', 'Eliminación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('info', 'Información'), ('error', 'Error')], default='info', max_length=15)),
                ('descripcion', models.TextField()),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=60, null=True)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácora',
                'ordering': ['-fecha'],
            },
        ),
    ]
