# Generated by Django 4.2.15 on 2026-07-31 07:47

import core.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='configuracion/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg']), core.validadores.validate_file_size_2mb]),
        ),
    ]
