# Generated by Django 4.2.15 on 2026-07-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_configuracion_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='token_ia_interna',
            field=models.CharField(blank=True, help_text='Token del operador para las funciones internas de IA (resúmenes, detección de datos, clasificación). No es la llave de ningún cliente.', max_length=300, null=True, verbose_name='Token global de IA'),
        ),
    ]
