# Generated by Django 4.2.15 on 2026-07-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracion_token_ia_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='modelo_ia_interna',
            field=models.CharField(blank=True, help_text='Vacío usa el modelo por defecto del proveedor.', max_length=120, null=True, verbose_name='Modelo del token global'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='proveedor_ia_interna',
            field=models.IntegerField(default=1, help_text='Con qué proveedor habla el token global.', verbose_name='Proveedor del token global'),
        ),
    ]
