# Generated by Django 4.2.15 on 2026-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracion_modelo_ia_interna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tika_activo',
            field=models.BooleanField(default=False, help_text='Extrae el texto de los documentos al indexar la base de conocimiento. Apagado usa solo los extractores locales (pypdf, python-docx).', verbose_name='Usar Apache Tika'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tika_url',
            field=models.CharField(blank=True, help_text='Ejemplo: https://tika.tu-dominio.com. Se le agrega /tika al llamar.', max_length=200, null=True, verbose_name='URL de Apache Tika'),
        ),
    ]
