# Generated by Django 4.2.15 on 2026-07-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío, es del operador y ve a todos los clientes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='clientes.cliente'),
        ),
    ]
