# Generated by Django 4.2.15 on 2026-07-31 00:44

import core.validadores
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telefonia', '0001_initial'),
        ('agentes_ia', '0002_initial'),
        ('ivr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('sentido', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], default='entrante', max_length=10)),
                ('driver', models.CharField(default='asterisk', help_text='Driver del proveedor que originó la llamada.', max_length=20)),
                ('call_id', models.CharField(blank=True, db_index=True, help_text='Identificador de la llamada en el carrier (CallSid, Call-ID SIP).', max_length=120, null=True)),
                ('stream_sid', models.CharField(blank=True, db_index=True, help_text='Identificador del stream de audio en tiempo real.', max_length=120, null=True)),
                ('numero_origen', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('numero_destino', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('pais_iso', models.CharField(blank=True, max_length=2, null=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('paso_actual', models.CharField(blank=True, max_length=40, null=True)),
                ('estado', models.CharField(choices=[('iniciando', 'Iniciando'), ('en_curso', 'En curso'), ('transfiriendo', 'Transfiriendo'), ('finalizada', 'Finalizada'), ('fallida', 'Fallida')], db_index=True, default='iniciando', max_length=15)),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta_ia', 'Resuelta por la IA'), ('transferida', 'Transferida a asesor'), ('abandonada', 'Abandonada por el cliente'), ('error', 'Error técnico')], default='pendiente', max_length=15)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('datos_capturados', models.JSONField(blank=True, default=dict, help_text='Variables recogidas durante el flujo: cédula, nombre, etc.')),
                ('resumen', models.TextField(blank=True, help_text='Resumen generado por la IA al cerrar.', null=True)),
                ('transcripcion', models.TextField(blank=True, null=True)),
                ('latencia_promedio_ms', models.IntegerField(default=0)),
                ('costo_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('agente_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='agentes_ia.agenteia')),
                ('flujo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='ivr.flujovoz')),
                ('numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='telefonia.numerotelefonico')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TurnoLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('ia', 'IA'), ('sistema', 'Sistema'), ('asesor', 'Asesor')], max_length=10)),
                ('texto', models.TextField(blank=True, null=True)),
                ('paso_codigo', models.CharField(blank=True, max_length=40, null=True)),
                ('dtmf', models.CharField(blank=True, max_length=20, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='turnos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3', 'ogg'])])),
                ('latencia_stt_ms', models.IntegerField(default=0)),
                ('latencia_llm_ms', models.IntegerField(default=0)),
                ('latencia_tts_ms', models.IntegerField(default=0)),
                ('latencia_ms', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='llamadas.llamada')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de la llamada',
                'verbose_name_plural': 'Turnos de la llamada',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('motivo', models.CharField(choices=[('solicitud_cliente', 'El cliente pidió un asesor'), ('paso_flujo', 'El flujo lo indica'), ('reintentos_agotados', 'No se entendió al cliente'), ('fuera_alcance', 'Consulta fuera del alcance de la IA'), ('error_tecnico', 'Error técnico')], default='solicitud_cliente', max_length=25)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_curso', 'En curso'), ('atendida', 'Atendida'), ('no_contestada', 'No contestada'), ('fallida', 'Fallida')], default='solicitada', max_length=15)),
                ('destino', models.CharField(blank=True, help_text='Número o extensión efectivamente marcada.', max_length=40, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='telefonia.asesorhumano')),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='llamadas.llamada')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='GrabacionLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('archivo', models.FileField(upload_to='grabaciones/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3', 'ogg']), core.validadores.validate_file_size_50mb])),
                ('formato', models.CharField(default='wav', max_length=10)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('almacenamiento', models.CharField(default='local', help_text='local, minio o s3 según la configuración del despliegue.', max_length=20)),
                ('llamada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grabacion', to='llamadas.llamada')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grabación',
                'verbose_name_plural': 'Grabaciones',
            },
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['estado', '-fecha_inicio'], name='llamadas_ll_estado_d857c9_idx'),
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['numero_origen'], name='llamadas_ll_numero__9f42d0_idx'),
        ),
    ]
