# Generated by Django 4.2.15 on 2026-07-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('llamadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='cliente',
            field=models.ForeignKey(help_text='Se copia del número al iniciar la llamada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llamadas', to='clientes.cliente'),
        ),
    ]
