# Generated by Django 4.2.15 on 2026-08-01 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_cliente_inicial'),
        ('llamadas', '0002_llamada_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('numero', models.CharField(db_index=True, help_text='Número desde el que llamó, en E.164.', max_length=25)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_iso', models.CharField(blank=True, max_length=2, null=True)),
                ('ultimo_motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('total_llamadas', models.IntegerField(default=0)),
                ('segundos_totales', models.IntegerField(default=0)),
                ('primera_llamada', models.DateTimeField(blank=True, null=True)),
                ('ultima_llamada', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='clientes.cliente')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-ultima_llamada'],
                'unique_together': {('cliente', 'numero')},
            },
        ),
    ]
