# Generated by Django 4.2.15 on 2026-07-31 00:44

import core.validadores
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ivr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorTelefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=80)),
                ('driver', models.CharField(choices=[('asterisk', 'Asterisk / FreeSWITCH auto-hospedado (gratuito)'), ('sip_generico', 'Troncal SIP genérica'), ('twilio', 'Twilio'), ('telnyx', 'Telnyx'), ('plivo', 'Plivo'), ('signalwire', 'SignalWire'), ('webrtc', 'WebRTC / navegador (pruebas)')], default='asterisk', help_text='Determina cómo se contesta la llamada y cómo se envía el audio.', max_length=20)),
                ('base_url', models.CharField(blank=True, help_text='Endpoint de la API del proveedor. Vacío para Asterisk local.', max_length=200, null=True)),
                ('cuenta_sid', models.CharField(blank=True, help_text='Account SID / API user del proveedor.', max_length=120, null=True)),
                ('token', models.CharField(blank=True, help_text='Auth token / API key del proveedor.', max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('costo_minuto_entrante', models.DecimalField(decimal_places=4, default=0, help_text='Costo por minuto entrante en USD (0 si es auto-hospedado).', max_digits=8)),
                ('costo_mensual_did', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor de telefonía',
                'verbose_name_plural': 'Proveedores de telefonía',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TroncalSIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=80)),
                ('host', models.CharField(max_length=120)),
                ('puerto', models.IntegerField(default=5060)),
                ('transporte', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS'), ('wss', 'WSS (WebRTC)')], default='udp', max_length=5)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('clave', models.CharField(blank=True, max_length=200, null=True)),
                ('contexto', models.CharField(default='desde-troncal', help_text='Contexto del dialplan de Asterisk que recibe las llamadas.', max_length=80)),
                ('codec_preferido', models.CharField(default='alaw', help_text='alaw/ulaw para telefonía tradicional, opus para WebRTC.', max_length=20)),
                ('registrar', models.BooleanField(default=True, help_text='Enviar REGISTER al proveedor.')),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troncales', to='telefonia.proveedortelefonia')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Troncal SIP',
                'verbose_name_plural': 'Troncales SIP',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NumeroTelefonico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('numero', models.CharField(help_text='Formato internacional E.164, ejemplo +593987654321.', max_length=20, unique=True, validators=[core.validadores.validar_e164])),
                ('pais_iso', models.CharField(default='EC', help_text='ISO 3166-1 alfa-2: EC, US, ES, MX, CO.', max_length=2)),
                ('prefijo_pais', models.CharField(default='593', max_length=5)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo', models.CharField(choices=[('local', 'Local / fijo'), ('movil', 'Móvil'), ('tollfree', 'Toll free (0800)'), ('nacional', 'Nacional')], default='local', max_length=10)),
                ('idioma', models.CharField(default='es', help_text='Idioma de atención: es, en, pt. Define STT y voz TTS.', max_length=10)),
                ('zona_horaria', models.CharField(default='America/Guayaquil', max_length=60)),
                ('concurrencia_maxima', models.IntegerField(default=4, help_text='Llamadas simultáneas permitidas en este número.')),
                ('minutos_incluidos', models.IntegerField(default=3500)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('flujo', models.ForeignKey(blank=True, help_text='Flujo IVR que atiende este número.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros', to='ivr.flujovoz')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeros', to='telefonia.proveedortelefonia')),
                ('troncal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros', to='telefonia.troncalsip')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Número telefónico',
                'verbose_name_plural': 'Números telefónicos',
                'ordering': ['pais_iso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AudioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=120)),
                ('archivo', models.FileField(upload_to='audios/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3', 'ogg']), core.validadores.validate_file_size_2mb])),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio del sistema',
                'verbose_name_plural': 'Audios del sistema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsesorHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=120)),
                ('numero_destino', models.CharField(blank=True, help_text='Celular o fijo en E.164 al que se reenvía la llamada.', max_length=20, null=True, validators=[core.validadores.validar_e164])),
                ('extension_sip', models.CharField(blank=True, help_text='Extensión interna del softphone, ejemplo 1001.', max_length=40, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('departamento', models.CharField(blank=True, max_length=80, null=True)),
                ('horario', models.CharField(choices=[('siempre', '24/7'), ('laboral', 'Lunes a viernes 08:00 - 18:00'), ('extendido', 'Lunes a sábado 08:00 - 20:00')], default='laboral', max_length=15)),
                ('prioridad', models.IntegerField(default=1, help_text='Menor número = se intenta primero.')),
                ('disponible', models.BooleanField(default=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asesor humano',
                'verbose_name_plural': 'Asesores humanos',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
    ]
