# Generated by Django 4.2.15 on 2026-07-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('telefonia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorhumano',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asesores', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='numerotelefonico',
            name='cliente',
            field=models.ForeignKey(help_text='Dueño de este número.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='numeros', to='clientes.cliente'),
        ),
    ]
