# Generated by Django 4.2.15 on 2026-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0002_asesorhumano_cliente_numerotelefonico_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorhumano',
            name='clave_sip',
            field=models.CharField(blank=True, help_text='Clave con la que el softphone se registra. Se usa al generar la configuración de Asterisk.', max_length=80, null=True),
        ),
    ]
