# Generated by Django 4.2.15 on 2026-08-01 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0007_alter_apikeyia_options_apikeyia_por_defecto'),
        ('telefonia', '0003_asesorhumano_clave_sip'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerotelefonico',
            name='agente_ia',
            field=models.ForeignKey(blank=True, help_text='Agente que responde en este número. Vacío usa el del flujo, que es lo normal: solo se llena cuando el mismo flujo debe sonar distinto según el número que marcaron.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros', to='agentes_ia.agenteia'),
        ),
    ]
