# Generated by Django 4.2.15 on 2026-07-31 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentes_ia', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('saludo', models.TextField(default='Hola, gracias por llamar. Soy el asistente virtual, ¿en qué puedo ayudarte?')),
                ('despedida', models.TextField(default='Gracias por comunicarte. Que tengas un excelente día.')),
                ('mensaje_error', models.TextField(default='No te entendí. ¿Puedes repetirlo por favor?')),
                ('max_reintentos', models.IntegerField(default=2)),
                ('segundos_espera_respuesta', models.IntegerField(default=8)),
                ('grabar_llamada', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Flujo IVR',
                'verbose_name_plural': 'Flujos IVR',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('tecla', models.CharField(blank=True, help_text='Dígito DTMF: 1, 2, 3, 0, *, #.', max_length=2, null=True)),
                ('frases', models.CharField(blank=True, help_text='Frases separadas por coma que activan la opción por voz.', max_length=300, null=True)),
                ('etiqueta', models.CharField(max_length=120)),
                ('orden', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Opción del menú',
                'verbose_name_plural': 'Opciones del menú',
                'ordering': ['paso', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PasoVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('codigo', models.SlugField(help_text='Identificador corto del paso, ejemplo: menu_principal.', max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('mensaje', 'Mensaje hablado'), ('menu', 'Menú de opciones (DTMF + voz)'), ('captura', 'Captura de dato'), ('agente_ia', 'Conversación con agente IA'), ('transferencia', 'Transferencia a asesor humano'), ('condicion', 'Condición sobre una variable'), ('webhook', 'Llamada a API externa'), ('colgar', 'Finalizar llamada')], default='mensaje', max_length=15)),
                ('orden', models.IntegerField(default=1)),
                ('texto', models.TextField(blank=True, help_text='Lo que dice la IA. Admite variables: {nombre}, {cedula}.', null=True)),
                ('variable', models.SlugField(blank=True, help_text='Nombre de la variable donde se guarda el dato capturado.', max_length=40, null=True)),
                ('validacion', models.CharField(choices=[('libre', 'Texto libre'), ('numero', 'Solo números'), ('cedula_ec', 'Cédula ecuatoriana'), ('documento', 'Documento genérico (5 a 15 dígitos)'), ('telefono', 'Teléfono E.164'), ('correo', 'Correo electrónico'), ('monto', 'Monto / decimal'), ('fecha', 'Fecha'), ('si_no', 'Sí / No')], default='libre', max_length=15)),
                ('modo_captura', models.CharField(choices=[('hibrido', 'Híbrido (teclado o voz)'), ('dtmf', 'Solo teclado (DTMF)'), ('voz', 'Solo voz')], default='hibrido', max_length=10)),
                ('longitud_minima', models.IntegerField(default=0)),
                ('longitud_maxima', models.IntegerField(default=0)),
                ('max_turnos_ia', models.IntegerField(default=8, help_text='Tope de turnos antes de continuar el flujo.')),
                ('expresion', models.CharField(blank=True, help_text='Condición evaluada sobre variables, ejemplo: monto > 100.', max_length=200, null=True)),
                ('url_webhook', models.CharField(blank=True, max_length=300, null=True)),
                ('metodo_webhook', models.CharField(default='POST', max_length=6)),
                ('agente_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos', to='agentes_ia.agenteia')),
            ],
            options={
                'verbose_name': 'Paso del flujo',
                'verbose_name_plural': 'Pasos del flujo',
                'ordering': ['flujo', 'orden', 'id'],
            },
        ),
    ]
