# Generated by Django 4.2.15 on 2026-07-31 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telefonia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ivr', '0001_initial'),
        ('agentes_ia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasovoz',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos', to='telefonia.asesorhumano'),
        ),
        migrations.AddField(
            model_name='pasovoz',
            name='audio',
            field=models.ForeignKey(blank=True, help_text='Audio pregrabado en lugar del TTS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos', to='telefonia.audiosistema'),
        ),
        migrations.AddField(
            model_name='pasovoz',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='ivr.flujovoz'),
        ),
        migrations.AddField(
            model_name='pasovoz',
            name='paso_error',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_error', to='ivr.pasovoz'),
        ),
        migrations.AddField(
            model_name='pasovoz',
            name='paso_siguiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_previos', to='ivr.pasovoz'),
        ),
        migrations.AddField(
            model_name='pasovoz',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasovoz',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcionpaso',
            name='paso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='ivr.pasovoz'),
        ),
        migrations.AddField(
            model_name='opcionpaso',
            name='paso_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_entrantes', to='ivr.pasovoz'),
        ),
        migrations.AddField(
            model_name='opcionpaso',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcionpaso',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flujovoz',
            name='agente_ia',
            field=models.ForeignKey(blank=True, help_text='Agente que responde las preguntas abiertas del flujo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos', to='agentes_ia.agenteia'),
        ),
        migrations.AddField(
            model_name='flujovoz',
            name='asesor_respaldo',
            field=models.ForeignKey(blank=True, help_text='A quién se transfiere si el flujo falla o el cliente lo pide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_respaldo', to='telefonia.asesorhumano'),
        ),
        migrations.AddField(
            model_name='flujovoz',
            name='paso_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_iniciados', to='ivr.pasovoz'),
        ),
        migrations.AddField(
            model_name='flujovoz',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flujovoz',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pasovoz',
            unique_together={('flujo', 'codigo')},
        ),
    ]
