# Generated by Django 4.2.15 on 2026-07-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujovoz',
            name='menu_cae_en_agente',
            field=models.BooleanField(default=True, help_text='Si el cliente dice algo que no coincide con ninguna opción del menú, responde el agente IA en lugar de repetir el menú.'),
        ),
    ]
