# Generated by Django 4.2.15 on 2026-07-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ivr', '0003_flujovoz_menu_cae_en_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujovoz',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flujos', to='clientes.cliente'),
        ),
    ]
