# Generated by Django 4.2.15 on 2026-07-31 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=120)),
                ('url', models.CharField(help_text='Ruta del sistema, con barra inicial y final: /llamadas/listado/', max_length=140, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('icono', models.CharField(blank=True, max_length=60, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('visible_menu', models.BooleanField(default=True, help_text='Desmarcado, el módulo sigue protegido pero no aparece en el menú lateral.')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Módulo (URL)',
                'verbose_name_plural': 'Módulos (URLs)',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModuloGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=120)),
                ('icono', models.CharField(blank=True, max_length=60, null=True)),
                ('prioridad', models.IntegerField(default=10, help_text='Menor número, más arriba en el menú.')),
                ('modulos', models.ManyToManyField(blank=True, related_name='grupos_menu', to='seguridad.modulo')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sección del menú',
                'verbose_name_plural': 'Secciones del menú',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GroupModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='auth.group')),
                ('modulos', models.ManyToManyField(blank=True, related_name='roles_asignados', to='seguridad.modulo')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permisos del rol',
                'verbose_name_plural': 'Permisos de los roles',
                'ordering': ['group__name'],
            },
        ),
    ]
