# Generated by Django 4.2.15 on 2026-08-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='perfil',
            field=models.CharField(choices=[('ambos', 'Administrador y cliente'), ('administrador', 'Solo el administrador'), ('cliente', 'Solo el cliente')], default='ambos', help_text='Para quién es esta pantalla. «Solo el administrador» la esconde de los clientes aunque su rol la tenga asignada: sirve para lo que lleva datos del servidor o de otros clientes.', max_length=15),
        ),
    ]
