# Generated by Django 4.2.15 on 2026-07-31 00:44

import core.validadores
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, help_text='Qué hace este agente y para qué cliente trabaja.', null=True)),
                ('prompt_sistema', models.TextField(default='Eres un asistente telefónico. Respondes en español neutro, en máximo dos oraciones cortas, con lenguaje natural para ser escuchado por teléfono. Nunca inventas datos: si no está en el contexto, ofreces transferir con un asesor.')),
                ('tono', models.CharField(choices=[('cordial', 'Cordial y cercano'), ('formal', 'Formal y corporativo'), ('comercial', 'Comercial y persuasivo'), ('tecnico', 'Técnico y preciso')], default='cordial', max_length=15)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('temperatura', models.FloatField(default=0.3)),
                ('max_tokens_respuesta', models.IntegerField(default=220)),
                ('maximo_oraciones', models.IntegerField(default=2, help_text='Tope de oraciones por respuesta hablada.')),
                ('usar_rag', models.BooleanField(default=True)),
                ('fragmentos_contexto', models.IntegerField(default=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agente IA',
                'verbose_name_plural': 'Agentes IA',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ApiKeyIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('alias', models.CharField(help_text='Nombre interno de la llave, ejemplo: gemini-produccion.', max_length=80)),
                ('proveedor', models.IntegerField(choices=[(1, 'Google Gemini (capa gratuita)'), (2, 'Groq (capa gratuita)'), (3, 'OpenRouter (modelos :free)'), (4, 'Ollama local (auto-hospedado)'), (5, 'Compatible con OpenAI')], default=1)),
                ('clave', models.CharField(blank=True, help_text='Vacío para Ollama local, que no requiere llave.', max_length=300, null=True)),
                ('modelo', models.CharField(blank=True, help_text='Vacío usa el modelo por defecto del proveedor.', max_length=120, null=True)),
                ('base_url', models.CharField(blank=True, help_text='Endpoint alterno para proveedores auto-hospedados.', max_length=200, null=True)),
                ('limite_mensual_llamadas', models.IntegerField(default=0, help_text='0 = sin límite.')),
                ('consumo_tokens_entrada', models.BigIntegerField(default=0, editable=False)),
                ('consumo_tokens_salida', models.BigIntegerField(default=0, editable=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Llave de IA',
                'verbose_name_plural': 'Llaves de IA',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ColeccionConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fragmentos_indexados', models.IntegerField(default=0, editable=False)),
                ('fecha_indexacion', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Colección de conocimiento',
                'verbose_name_plural': 'Colecciones de conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('modelo', models.CharField(blank=True, max_length=120, null=True)),
                ('tokens_entrada', models.IntegerField(default=0)),
                ('tokens_salida', models.IntegerField(default=0)),
                ('latencia_ms', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consumo de IA',
                'verbose_name_plural': 'Consumos de IA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='conocimiento/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'md', 'docx', 'csv', 'html']), core.validadores.validate_file_size_20mb])),
                ('contenido', models.TextField(blank=True, help_text='Texto plano. Se completa solo al procesar el archivo.', null=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='agentes_ia.coleccionconocimiento')),
            ],
            options={
                'verbose_name': 'Documento de conocimiento',
                'verbose_name_plural': 'Documentos de conocimiento',
                'ordering': ['titulo'],
            },
        ),
    ]
