# Generated by Django 4.2.15 on 2026-07-31 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyia',
            name='modelo_embeddings',
            field=models.CharField(blank=True, help_text='Modelo de embeddings para el RAG. Solo aplica a proveedores que los ofrecen.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='coleccionconocimiento',
            name='apikey_embeddings',
            field=models.ForeignKey(blank=True, help_text='Llave usada para generar embeddings (solo con motor Gemini).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colecciones', to='agentes_ia.apikeyia'),
        ),
        migrations.AddField(
            model_name='coleccionconocimiento',
            name='backend',
            field=models.CharField(choices=[('local', 'Local (numpy en el servidor)'), ('weaviate', 'Weaviate (multi-tenant)')], default='local', help_text='Dónde vive el índice vectorial de esta colección.', max_length=10),
        ),
        migrations.AddField(
            model_name='coleccionconocimiento',
            name='motor_embeddings',
            field=models.CharField(choices=[('gemini', 'Gemini (API, capa gratuita)'), ('local', 'Local (sentence-transformers)')], default='gemini', help_text='Cómo se vectoriza el texto.', max_length=10),
        ),
        migrations.AddField(
            model_name='consumoia',
            name='apikey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='agentes_ia.apikeyia'),
        ),
        migrations.AddField(
            model_name='consumoia',
            name='costo_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Estimado según el tarifario del proveedor.', max_digits=12),
        ),
        migrations.AddField(
            model_name='consumoia',
            name='error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consumoia',
            name='proveedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consumoia',
            name='uso_rag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apikeyia',
            name='proveedor',
            field=models.IntegerField(choices=[(1, 'Google Gemini (capa gratuita)'), (2, 'Groq (capa gratuita)'), (3, 'OpenRouter (modelos :free)'), (4, 'Ollama local (auto-hospedado)'), (5, 'Compatible con OpenAI'), (6, 'Ollama Cloud')], default=1),
        ),
        migrations.AlterField(
            model_name='consumoia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='consumoia',
            index=models.Index(fields=['-fecha', 'agente'], name='agentes_ia__fecha_c111be_idx'),
        ),
    ]
