# Generated by Django 4.2.15 on 2026-07-31 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('agentes_ia', '0004_apikeyia_modelo_embeddings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteia',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agentes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='coleccionconocimiento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colecciones', to='clientes.cliente'),
        ),
    ]
