# Generated by Django 4.2.15 on 2026-07-31 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_inicial'),
        ('agentes_ia', '0005_agenteia_cliente_coleccionconocimiento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyia',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Vacío: llave por defecto, disponible para todos los clientes. Con cliente: solo la usan sus agentes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apikeys', to='clientes.cliente'),
        ),
    ]
