# Generated by Django 4.2.15 on 2026-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0006_apikeyia_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikeyia',
            options={'ordering': ['-por_defecto', 'alias'], 'verbose_name': 'Llave de IA', 'verbose_name_plural': 'Llaves de IA'},
        ),
        migrations.AddField(
            model_name='apikeyia',
            name='por_defecto',
            field=models.BooleanField(default=False, help_text='La que usan los agentes que no eligen una llave propia. Solo puede haber una por defecto en cada ámbito.', verbose_name='Por defecto'),
        ),
    ]
