# Generated by Django 4.2.15 on 2026-07-31 07:53

import core.validadores
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('status', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(help_text='Nombre comercial con el que se identifica en el panel.', max_length=120, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=180, null=True)),
                ('identificacion', models.CharField(blank=True, help_text='RUC, NIT o identificación fiscal.', max_length=20, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='clientes/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg']), core.validadores.validate_file_size_2mb])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('zona_horaria', models.CharField(default='America/Guayaquil', max_length=60)),
                ('minutos_incluidos_mes', models.IntegerField(default=3500, help_text='Minutos del plan contratado, como referencia.')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, sus números dejan de atender llamadas.')),
                ('usuario_creacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
